spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
      ssl:
        trust-store-location: "classpath:certs/kafka.consumer.keystore.jks"
        trust-store-password: "confluent"
        key-store-location: "classpath:certs/kafka.consumer.truststore.jks"
        key-store-password: "confluent"
        key-password: "confluent"
      properties:
        security.protocol: "SSL"
        ssl.endpoint.identification.algorithm:
    bootstrap-servers: 192.168.1.39:39092, 192.168.1.39:29092, 192.168.1.39:19092
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
