spring:
  kafka:
    template:
      default-topic: library-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: 192.168.1.39:9092, 192.168.1.39:9093, 192.168.1.39:9094
