spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
